### ISSUE TITLE
mjcf module incorrectly requires all plugin elements to have a name attribute

### ISSUE THREAD

**Issue by kgaranger** [google-deepmind/dm_control#450] opened 2024-02-06 02:20 UTC
The various `plugin` elements have a name attribute defined in [schema.xml](https://github.com/google-deepmind/dm_control/blob/main/dm_control/mjcf/schema.xml) of the mjcf module.
However, some plugins like body plugins do not have a name in `mujoco`. Because `dm_control` automatically gives a name to plugin elements by default, generated MJCF files may result in an error when using them with `mujoco`.

**Comment by nimrod-gileadi** [comment] 2024-09-02 11:52
I can't reproduce the issue of dm_control generating names for plugin elements. Maybe it was incidentally fixed by d4e76b3da3d23997ef008c78d9088e795427bb35, but you were using an older version?

Any way you're right that the name attribute shouldn't be there in the schema and I'll remove it. Sorry for missing this issue for so long.

**Closed** 2024-09-02 14:51 UTC
